default:
  interruptible: true
  image: node:lts-alpine

stages:
  - dependencies
  - quality
  - assemble
  - deploy

before_script:
  - apk update && apk add --no-cache openssh-client

variables:
  NODE_OPTIONS: "--max-old-space-size=4096"
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  CI_DEBUG_TRACE: "true"

install_dependencies:
  stage: dependencies
  script:
    - cd front-angular && npm install --prefer-offline
    - cd ../api-nest-pando && npm install --prefer-offline
  cache:
    key:
      files:
        - front-angular/package.json
        - api-nest-pando/package.json
    paths:
      - front-angular/node_modules
      - api-nest-pando/node_modules

quality:
  stage: quality
  script:
    - cd front-angular && npm run test
    - cd ../api-nest-pando && npm run test
    - npm run lint
  cache:
    key:
      files:
        - front-angular/package.json
        - api-nest-pando/package.json
    paths:
      - front-angular/node_modules
      - api-nest-pando/node_modules
    policy: pull

assemble:
  stage: assemble
  script:
    - cd front-angular && npm run build
    - cd ../api-nest-pando && npm run build
  artifacts:
    paths:
      - front-angular/dist
      - api-nest-pando/dist
  cache:
    key:
      files:
        - front-angular/package.json
        - api-nest-pando/package.json
    paths:
      - front-angular/node_modules
      - api-nest-pando/node_modules
    policy: pull

deploy:
  stage: deploy
  script:
    - ssh -p 65002 u641340594@154.49.245.22
    - scp -o StrictHostKeyChecking=no -P 65002 -r C:/Users/hamid/WebstormProjects/hybrid-sites/front-angular/dist/pandoramid/* u641340594@154.49.245.22:/home/u641340594/public_html
  environment:
    name: production
  only:
    - master
