default:
  interruptible: true
  image: node:lts-alpine

stages:
  - dependencies
  - quality
  - assemble
  - deploy

before_script:
  - apk update && apk add --no-cache openssh-client
  - apk add --no-cache lftp

variables:
  NODE_OPTIONS: "--max-old-space-size=4096"
  FTP_USERNAME: u641340594
  FTP_PASSWORD: Aburame13$2023
  CI_DEBUG_TRACE: "true"

install_dependencies:
  stage: dependencies
  script:
    - cd front-angular && npm install --prefer-offline
    - cd ../api-nest-pando && npm install --prefer-offline
  cache:
    key:
      files:
        - front-angular/package.json
        - api-nest-pando/package.json
    paths:
      - front-angular/node_modules
      - api-nest-pando/node_modules

quality:
  stage: quality
  script:
    - cd front-angular && npm run test
    - cd ../api-nest-pando && npm run test
    - npm run lint
  cache:
    key:
      files:
        - front-angular/package.json
        - api-nest-pando/package.json
    paths:
      - front-angular/node_modules
      - api-nest-pando/node_modules
    policy: pull

assemble:
  stage: assemble
  script:
    - cd front-angular && npm run build
    - cd ../api-nest-pando && npm run build
  artifacts:
    paths:
      - front-angular/dist
      - api-nest-pando/dist
  cache:
    key:
      files:
        - front-angular/package.json
        - api-nest-pando/package.json
    paths:
      - front-angular/node_modules
      - api-nest-pando/node_modules
    policy: pull

deploy:
  stage: deploy
  script:
    - echo "$FTP_USERNAME"
    - echo "FTP Password:" $FTP_PASSWORD
    - ls
    - cd front-angular/dist/
#    - lftp -e "set ssl:verify-certificate no; mirror -R pandoramid /home/u641340594/domains/pandoramid.com/public_html" -u $FTP_USERNAME,$FTP_PASSWORD, 21 ftp://ftp.pandoramid.com
    - lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD ftp://pandoramid.com; mirror -R pandoramid/* /domains/pandoramid.com/public_html"
  environment:
    name: production
  only:
    - master
