default:
  interruptible: true
  image: node:lts-alpine

stages:
  - dependencies
  - quality
  - assemble
  - deploy

before_script:
  - apk update && apk add --no-cache openssh-client
  - apk add --no-cache lftp

variables:
  NODE_OPTIONS: "--max-old-space-size=4096"
  CI_DEBUG_TRACE: "true"

install_dependencies:
  stage: dependencies
  script:
    - cd front-angular && npm install --prefer-offline || { echo "Failed to install front-end dependencies"; exit 1; }
    - cd ../api-nest-pando && npm install --prefer-offline || { echo "Failed to install backend dependencies"; exit 1; }
  cache:
    key:
      files:
        - front-angular/package.json
        - api-nest-pando/package.json
    paths:
      - front-angular/node_modules
      - api-nest-pando/node_modules

quality:
  stage: quality
  script:
    - cd front-angular && npm run test || { echo "Front-end tests failed"; exit 1; }
    - cd ../api-nest-pando && npm run test || { echo "Backend tests failed"; exit 1; }
    - npm run lint || { echo "Linting failed"; exit 1; }
  cache:
    key:
      files:
        - front-angular/package.json
        - api-nest-pando/package.json
    paths:
      - front-angular/node_modules
      - api-nest-pando/node_modules
    policy: pull

assemble:
  stage: assemble
  script:
    - cd front-angular && npm run build || { echo "Front-end build failed"; exit 1; }
    - cd ../api-nest-pando && npm run build || { echo "Backend build failed"; exit 1; }
  artifacts:
    paths:
      - front-angular/dist
      - api-nest-pando/dist
  cache:
    key:
      files:
        - front-angular/package.json
        - api-nest-pando/package.json
    paths:
      - front-angular/node_modules
      - api-nest-pando/node_modules
    policy: pull

deploy:
  stage: deploy
  script:
    - lftp -c "set ssl:verify-certificate no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R front-angular/dist/pandoramid/ /domains/pandoramid.com/public_html" || { echo "Deployment failed"; exit 1; }
  environment:
    name: production
  only:
    - master

